//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockScraper.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Filing
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Filing()
        {
            this.Shares = new HashSet<Share>();
            this.UnknownShares = new HashSet<UnknownShare>();
        }
    
        public int FilingId { get; set; }
        public int HedgeFundId { get; set; }
        public int FormTypeId { get; set; }
        public int MasterIndexId { get; set; }
        public System.DateTime Date { get; set; }
        public string Url { get; set; }
    
        public virtual FormType FormType { get; set; }
        public virtual HedgeFund HedgeFund { get; set; }
        public virtual MasterIndex MasterIndex { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Share> Shares { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UnknownShare> UnknownShares { get; set; }
    }
}
