//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockScraper.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SecurityMap
    {
        public int SecurityMapId { get; set; }
        public string Name { get; set; }
        public string Cusip { get; set; }
        public Nullable<int> SecurityId { get; set; }
    
        public virtual Security Security { get; set; }
    }
}
