//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockScraper.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnknownShare
    {
        public int UnknownShareId { get; set; }
        public int FilingId { get; set; }
        public int Number { get; set; }
        public string Type { get; set; }
        public decimal Value { get; set; }
        public string NameOfIssuer { get; set; }
        public string Cusip { get; set; }
        public Nullable<int> SecurityId { get; set; }
    
        public virtual Filing Filing { get; set; }
    }
}
